### ISSUE TITLE
Feature request: cancel without QR code before alarm goes off

### ISSUE THREAD

**Issue by Marmotian** [sweakpl/qralarm-android#15]
I think it should be possible to cancel the alarm any time before it is set to go off without needing to use the QR code. This could be made optional through the Settings menu.

**Comment by domportera** [comment]
Looks like we thought of the same thing. I just submitted a [pull request](just submitted a pull request for this. If accepted, this can be marked as closed) for this. If accepted, this can be marked as closed

**Comment by sweakpl** [comment]
I've decided not to implement this functionality as I believe it is contrary to the app's purpose which is always making the user dismiss the alarm by scanning the code.

**Comment by domportera** [comment]
I understand that. But when laying in bed at night trying to set my alarm and I accidentally put in the wrong time (or an AM/PM mixup), getting out of bed to scan a code on the other side of my apartment is a real bummer. maybe if there's an option/default behavior of this option of requiring a scan starting at ~an hour or two before it goes off? im not gonna die without this feature on main since i have it now but I imagine it's not an uncommon situation for a lot of users

**Comment by sweakpl** [comment]
This issue is addressed with the snackbar at the bottom of the screen after the user sets the alarm. I have in mind that for some people the snackbar duration might be too short though.

**Comment by domportera** [comment]
yes the snackbar works. i just know that I've been in bed for ~30 minutes after setting the alarm, realized i cant sleep and would like to sleep longer, and had to make the trek
