### ISSUE TITLE
Time scrolling bugs out

### ISSUE THREAD

**Issue by BloodRaven0** [sweakpl/qralarm-android#28]
When scrolling the time, the numbers above the current time disappear, and when this happens, the alarm is set to the bottom numbers (1 hour and 1 minute forward of what they should be)

These fading numbers above and below might look fancy, but their implementation seems to be buggy.
Could we get a rollback to the previous time selection menu until this is debugged?

Happens on both android 10 and android 13, different phones and vendors, from atleast version 1.5 (haven't tested earlier versions)

![Screenshot_20230910-100602_QRAlarm](https://github.com/sweakpl/qralarm-android/assets/42444745/109d71bc-ea71-42ea-96b6-750d70643987)

**Comment by sweakpl** [comment]
Could you please provide a video of this issue? I am not sure if this is a breaking bug.

The time picker is using a native Android time picker since the previous version of it was lacking the fling functionality and was really difficult to change.

Native time picker does support flinging so I've decided to stick with it. I've modified the style of it and I suppose that the bigger font that I've applied is responsible for this numbers disappearing.

I don't want to fall back to the previous implementation since the lack of flinging is far more problematic for the general user experience than this new problem unless it is somehow more troublesome than I think.

**Comment by sweakpl** [comment]
I've been trying to reproduce this bug on various devices, but I really could not 😕 Is there anything in common in the devices you have tested on? Like phone manufacturer or Android custom ROM? Also, does the notification in the app bar show the wrong alarm time as well when this bug is happening?

**Comment by BloodRaven0** [comment]
One phone is on Android 10, rooted with custom rom (resurrection remix) phone is Poco x3 nfc, the other is pretty much a stock Samsung android 13, galaxy a54.

The bug is in the UI, so when it sets the alarm for a wrong time, its reflected in the notification as well. My guess is that it's set to show 3 rows of numbers and set the alarm to the second row, so when the first disappears for whatever reason, it sets it to the one below?

I can try to install old versions to find which is the first one with the bug if that would help.

**Comment by sweakpl** [comment]
Thanks for information. There's no need to do anything on your side, thank you. This is an internal Android bug and probably belongs to the Google Issue Tracker as like I said, the time picker is a native Android time picker - not my own implementation. I will have to test this in separation as soon as I can.

**Comment by sweakpl** [comment]
I've investigated further and the bug was caused by too large font size of the time picker. I've decreased it and locked it so that user settings won't be able to increase its size. The change will be present in the future update.
