### ISSUE TITLE
Support Direct Boot (alarm before first unlock)

### ISSUE THREAD

**Issue by secretmango** [sweakpl/qralarm-android#34]
The alarm clock does not do anything if the device rebooted and it not yet unlocked.

I am not sure if the Camera could work here, so this alarm clock could be fundamentally incompatible.

But if you device reboots, for example on GrapheneOS where auto-reboot is used as a security measurement to clear the encryption keys from RAM or with automatic system updates with reboot, the clock would not go off.

The AOSP clock as well as [new-clock](https://github.com/qw123wh/new-clock) support direct boot, so they display the alarm on top of even the SIM card lock screen after a reboot.

**Comment by sweakpl** [comment]
Hey, thanks for reporting! I'm aware of this problem and actually at one point QRAlarm was considering direct boot. It has become problematic because of the use of the Jetpack DataStore framework which was trying to use the encrypted storage scope which was causing a crash.

Here is the Google Issue Tracker thread in which I reported my problem: https://issuetracker.google.com/issues/273326519

I've tried using the direct boot safety measures like `Context.createDeviceProtectedStorageContext()` which didn't work at that time and thus I've decided to, unfortunately, stop the support for direct boot in [this](https://github.com/sweakpl/qralarm-android/commit/8a6658f415d7476305ada5953322ecc06caa2acc) commit.

I still must admit that I might have not entirely explored the direct boot functionality so I would probably look into that issue again in the future.

**Comment by firefoxlover** [comment]
Thanks for the response!

**Comment by phanirithvij** [comment]
That bug on Google issue tracker was marked as won't fix.

**Comment by aviallon** [comment]
Perhaps you should use this : https://developer.android.com/reference/android/Manifest.permission#SCHEDULE_EXACT_ALARM

**Comment by sweakpl** [comment]
@aviallon This issue is already fixed since the release of QRAlarm 2.0 - the app works in direct boot mode no problem!
