### ISSUE TITLE
QRAlarm crashes when accessing the camera after a nightly phone restart

### ISSUE THREAD

**Issue by szeredniklaszlo** [sweakpl/qralarm-android#51]
Hello,

I’ve been using QRAlarm on my HONOR phone, and it works well under normal conditions. However, I’ve encountered an issue related to nightly phone restarts. Here's the detailed scenario:

1. I set my phone to automatically restart at 3:00 AM and turn back on at 7:00 AM.
2. My QRAlarm is set to go off at 8:00 AM.
3. After the restart, my phone requires me to enter the unlock code to access the device.
4. When the alarm sounds (because the alarm itself works), and I attempt to scan the QR code to turn it off, the app crashes while trying to access the camera for scanning.
5. As a result, the alarm stops without requiring me to scan the QR code, defeating the purpose of the app.

I’ve already ensured that:

- Battery optimization is disabled for QRAlarm.
- The app is allowed to start automatically and run in the background.
- All relevant permissions, including Camera access, are granted.
- The issue seems to be related to how the app interacts with the phone's lock state or permissions after a restart.

Steps to Reproduce:

1. Enable a scheduled restart on an HONOR phone (set to turn off and back on during the night).
2. Set a QRAlarm to go off after the restart.
3. Allow the phone to restart and lock.
4. Attempt to scan the QR code to disable the alarm.

**Expected Behavior:**
The app should access the camera and allow scanning of the QR code, even after a phone restart.

**Actual Behavior:**
The app crashes when attempting to access the camera, allowing the alarm to be dismissed without scanning the QR code.

**Device Information:**

- Device: HONOR Phone
- Android Version: [Include your phone's Android version]
- App Version: [Include the app version you're using]

**Additional Context:**
This issue does not occur when the phone is not restarted overnight. I can't provide logs because i can't start any log collector utility without unlocking my phone after the restart happens, and if i unlock my phone, i can't reproduce the error in the app without restarting (and turning off log collector for) my phone.

Thank you for looking into this issue!

**Comment by sweakpl** [comment]
Thank you for notifying me. I'm on it.

**Comment by sweakpl** [comment]
The issue was that the underlying `CameraX` library was not suited to work under the [direct boot](https://developer.android.com/privacy-and-security/direct-boot) conditions. More specifically when calling `ProcessCameraProvider.getInstance(context)`, when configuring the camera, the following code was called in the `CameraX` internals (you can look it up in the `CameraX` [source code](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/camera/camera-core/src/main/java/androidx/camera/core/CameraX.java) - line ~180):

```java
ServiceInfo serviceInfo = appContext.getPackageManager().getServiceInfo(
        new ComponentName(appContext, MetadataHolderService.class),
        PackageManager.GET_META_DATA | PackageManager.MATCH_DISABLED_COMPONENTS);
```

This code was trying to retrieve the CameraXConfig.Provider through meta-data provided by implementation library but instead was throwing `PackageManager.NameNotFoundException` which failed the whole camera initialization process.

At this point I've realized I shouldn't really expect `CameraX` maintainers to address this issue so I've created a workaround that would, before launching the camera, check whether we are operating in the direct boot mode using [UserManager.isUserUnlocked](https://developer.android.com/reference/android/os/UserManager#isUserUnlocked()):

```kotlin
val userManager = getSystemService(USER_SERVICE) as UserManager

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N &&
    !userManager.isUserUnlocked
) {
    // We are in the direct boot mode - request the user to unlock the device first...
}
```

This would avoid the crash as the camera would be launched after unlocking the device.

**Comment by szeredniklaszlo** [comment]
Thanks! You are fast, tomorrow I will not fall back asleep anymore xD

**Comment by sweakpl** [comment]
I have no choice but to be fast 😅 Whenever I hear of a bug or crash I know I could be also affected because QRAlarm is waking me up ever since it was released, so fixing those kinds of issues is always my main priority.
