### ISSUE TITLE
Temporary Mute adjust time

### ISSUE THREAD

**Issue by tiwey15** [sweakpl/qralarm-android#54]
Hey, Sweak! Great app. Thanks for all your work on this. I just bought the pro version 😁

The barcode that I scan is in my kitchen, and it takes longer than 15 seconds to go from my bed to the kitchen. Can we get a slider to adjust that time? Maybe 15-60 seconds? 30 seconds is good enough for me.

**Comment by sweakpl** [comment]
That's a good idea! I left it at 15 seconds because it was good for me, but I didn't give it a second thought really 😅.

I think I will just make a chooser for 0, 15, 30, 45 and 60 seconds so that it will be consistent with the rest of UI and I think this should be good enough. I will work on it as soon as I can.

Thank you for the feedback and support! 🙌
